# Variáveis globais da automação de deploy
app_root: /home/alessandro/late-prod
pm2_bin: /usr/bin/pm2
pm2_ecosystem: "{{ app_root }}/ecosystem.config.js"
repo_remote: origin
repo_branch: main
node_env: production
pm2_web_process: late-prod
pm2_extra_processes:
  - late-prod-email-worker
  - late-prod-export-worker
# Define se roda npm install (padrão true para garantir dependências)
pm_install: true
npm_bin: /usr/bin/npm
